# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meridian < Formula
  desc "A tool for getting information about your current location."
  homepage "https://github.com/mrflynn/meridian"
  version "0.1.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.4/meridian_0.1.4_darwin_amd64.tar.gz"
    sha256 "d737abbf76c896b63d0748e73ac71e4b290f26ac4914799a48b49d492ef0ea16"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.4/meridian_0.1.4_darwin_arm64.tar.gz"
    sha256 "477d5ba0d3d15e86ea194f92a0f222d0155d013a8044441f229f65c235cbd3b4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.4/meridian_0.1.4_linux_amd64.tar.gz"
    sha256 "cf1303279687000afbe1686d37a804251959f89986bbfb241188f006127e6f46"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.4/meridian_0.1.4_linux_arm64.tar.gz"
    sha256 "e24b2f74973a80e020349c2d1c745d0dce6b05037a50a0bace2736b4c62494ea"
  end

  def install
    bin.install "meridian"
  end

  def caveats; <<~EOS
    Run meridian info for a list of available data.
  EOS
  end
end
