# This file was generated by GoReleaser. DO NOT EDIT.
class Meridian < Formula
  desc "A tool for getting information about your current location."
  homepage "https://github.com/mrflynn/meridian"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.3/meridian_0.1.3_darwin_amd64.tar.gz"
    sha256 "f057a305aec897348a475220dc66276c7e712f90d975f7615b80abe9c6751c83"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.3/meridian_0.1.3_linux_amd64.tar.gz"
    sha256 "fb0ad72279311f25a8726f15ee5d4d5938daa17cfd57e9678ff264259aeeb555"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MrFlynn/meridian/releases/download/v0.1.3/meridian_0.1.3_linux_arm64.tar.gz"
    sha256 "e2310f5b611e69f14a35e0be056ca0343800082ff1bae759875cb1c509133993"
  end

  def install
    bin.install "meridian"
  end

  def caveats; <<~EOS
    Run meridian info for a list of available data.
  EOS
  end
end
